// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Chat
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Chat struct {
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto1.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Chat_Nil struct {
}

func (m *Chat_Nil) Reset()                    { *m = Chat_Nil{} }
func (m *Chat_Nil) String() string            { return proto1.CompactTextString(m) }
func (*Chat_Nil) ProtoMessage()               {}
func (*Chat_Nil) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Chat_List struct {
	Messages []*Chat_Message `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *Chat_List) Reset()                    { *m = Chat_List{} }
func (m *Chat_List) String() string            { return proto1.CompactTextString(m) }
func (*Chat_List) ProtoMessage()               {}
func (*Chat_List) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Chat_List) GetMessages() []*Chat_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Chat_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *Chat_Id) Reset()                    { *m = Chat_Id{} }
func (m *Chat_Id) String() string            { return proto1.CompactTextString(m) }
func (*Chat_Id) ProtoMessage()               {}
func (*Chat_Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Chat_Id) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Chat_Message struct {
	Id     uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
}

func (m *Chat_Message) Reset()                    { *m = Chat_Message{} }
func (m *Chat_Message) String() string            { return proto1.CompactTextString(m) }
func (*Chat_Message) ProtoMessage()               {}
func (*Chat_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Chat_Message) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat_Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Chat_Message) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Chat_Consumer struct {
	Id   uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	From int64  `protobuf:"varint,2,opt,name=From" json:"From,omitempty"`
}

func (m *Chat_Consumer) Reset()                    { *m = Chat_Consumer{} }
func (m *Chat_Consumer) String() string            { return proto1.CompactTextString(m) }
func (*Chat_Consumer) ProtoMessage()               {}
func (*Chat_Consumer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Chat_Consumer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat_Consumer) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type Chat_ConsumeRange struct {
	Id   uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	From int64  `protobuf:"varint,2,opt,name=From" json:"From,omitempty"`
	To   int64  `protobuf:"varint,3,opt,name=To" json:"To,omitempty"`
}

func (m *Chat_ConsumeRange) Reset()                    { *m = Chat_ConsumeRange{} }
func (m *Chat_ConsumeRange) String() string            { return proto1.CompactTextString(m) }
func (*Chat_ConsumeRange) ProtoMessage()               {}
func (*Chat_ConsumeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Chat_ConsumeRange) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat_ConsumeRange) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Chat_ConsumeRange) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

type Chat_ConsumeLatest struct {
	Id     uint64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Length int64  `protobuf:"varint,2,opt,name=Length" json:"Length,omitempty"`
}

func (m *Chat_ConsumeLatest) Reset()                    { *m = Chat_ConsumeLatest{} }
func (m *Chat_ConsumeLatest) String() string            { return proto1.CompactTextString(m) }
func (*Chat_ConsumeLatest) ProtoMessage()               {}
func (*Chat_ConsumeLatest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *Chat_ConsumeLatest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chat_ConsumeLatest) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto1.RegisterType((*Chat)(nil), "proto.Chat")
	proto1.RegisterType((*Chat_Nil)(nil), "proto.Chat.Nil")
	proto1.RegisterType((*Chat_List)(nil), "proto.Chat.List")
	proto1.RegisterType((*Chat_Id)(nil), "proto.Chat.Id")
	proto1.RegisterType((*Chat_Message)(nil), "proto.Chat.Message")
	proto1.RegisterType((*Chat_Consumer)(nil), "proto.Chat.Consumer")
	proto1.RegisterType((*Chat_ConsumeRange)(nil), "proto.Chat.ConsumeRange")
	proto1.RegisterType((*Chat_ConsumeLatest)(nil), "proto.Chat.ConsumeLatest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatService service

type ChatServiceClient interface {
	Subscribe(ctx context.Context, in *Chat_Consumer, opts ...grpc.CallOption) (ChatService_SubscribeClient, error)
	Reg(ctx context.Context, in *Chat_Id, opts ...grpc.CallOption) (*Chat_Nil, error)
	UnReg(ctx context.Context, in *Chat_Id, opts ...grpc.CallOption) (*Chat_Nil, error)
	Query(ctx context.Context, in *Chat_ConsumeRange, opts ...grpc.CallOption) (*Chat_List, error)
	Latest(ctx context.Context, in *Chat_ConsumeLatest, opts ...grpc.CallOption) (*Chat_List, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Subscribe(ctx context.Context, in *Chat_Consumer, opts ...grpc.CallOption) (ChatService_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChatService_serviceDesc.Streams[0], c.cc, "/proto.ChatService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_SubscribeClient interface {
	Recv() (*Chat_Message, error)
	grpc.ClientStream
}

type chatServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *chatServiceSubscribeClient) Recv() (*Chat_Message, error) {
	m := new(Chat_Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) Reg(ctx context.Context, in *Chat_Id, opts ...grpc.CallOption) (*Chat_Nil, error) {
	out := new(Chat_Nil)
	err := grpc.Invoke(ctx, "/proto.ChatService/Reg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UnReg(ctx context.Context, in *Chat_Id, opts ...grpc.CallOption) (*Chat_Nil, error) {
	out := new(Chat_Nil)
	err := grpc.Invoke(ctx, "/proto.ChatService/UnReg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Query(ctx context.Context, in *Chat_ConsumeRange, opts ...grpc.CallOption) (*Chat_List, error) {
	out := new(Chat_List)
	err := grpc.Invoke(ctx, "/proto.ChatService/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Latest(ctx context.Context, in *Chat_ConsumeLatest, opts ...grpc.CallOption) (*Chat_List, error) {
	out := new(Chat_List)
	err := grpc.Invoke(ctx, "/proto.ChatService/Latest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ChatService service

type ChatServiceServer interface {
	Subscribe(*Chat_Consumer, ChatService_SubscribeServer) error
	Reg(context.Context, *Chat_Id) (*Chat_Nil, error)
	UnReg(context.Context, *Chat_Id) (*Chat_Nil, error)
	Query(context.Context, *Chat_ConsumeRange) (*Chat_List, error)
	Latest(context.Context, *Chat_ConsumeLatest) (*Chat_List, error)
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Chat_Consumer)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Subscribe(m, &chatServiceSubscribeServer{stream})
}

type ChatService_SubscribeServer interface {
	Send(*Chat_Message) error
	grpc.ServerStream
}

type chatServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *chatServiceSubscribeServer) Send(m *Chat_Message) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_Reg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Reg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatService/Reg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Reg(ctx, req.(*Chat_Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UnReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UnReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatService/UnReg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UnReg(ctx, req.(*Chat_Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat_ConsumeRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Query(ctx, req.(*Chat_ConsumeRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Latest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chat_ConsumeLatest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Latest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatService/Latest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Latest(ctx, req.(*Chat_ConsumeLatest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reg",
			Handler:    _ChatService_Reg_Handler,
		},
		{
			MethodName: "UnReg",
			Handler:    _ChatService_UnReg_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ChatService_Query_Handler,
		},
		{
			MethodName: "Latest",
			Handler:    _ChatService_Latest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ChatService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto1.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x4e, 0xfa, 0x30,
	0x14, 0xcf, 0x3e, 0xff, 0xfc, 0x0f, 0x88, 0xe6, 0x48, 0xc8, 0xec, 0xd5, 0xe2, 0x85, 0xd9, 0xd5,
	0x34, 0x10, 0x83, 0xd7, 0x10, 0x4d, 0x48, 0x10, 0x63, 0xc1, 0x07, 0x18, 0xac, 0xc0, 0x12, 0x58,
	0x4d, 0xdb, 0x99, 0xf0, 0x00, 0xbe, 0x9f, 0x8f, 0x64, 0x56, 0xaa, 0x59, 0x60, 0x17, 0xde, 0xb4,
	0xe7, 0xf4, 0xf7, 0x71, 0xda, 0x5f, 0x0a, 0xb0, 0xdc, 0x24, 0x2a, 0x7e, 0x17, 0x5c, 0x71, 0xf4,
	0xf4, 0x76, 0xfd, 0x65, 0x83, 0x3b, 0xda, 0x24, 0x8a, 0x78, 0xe0, 0x4c, 0xb3, 0x2d, 0x19, 0x80,
	0x3b, 0xc9, 0xa4, 0xc2, 0x5b, 0x68, 0x3c, 0x33, 0x29, 0x93, 0x35, 0x93, 0x81, 0x15, 0x3a, 0x51,
	0xb3, 0x77, 0x79, 0x10, 0xc6, 0x25, 0x3b, 0x36, 0x18, 0xfd, 0x25, 0x91, 0x0e, 0xd8, 0xe3, 0x14,
	0xdb, 0xe5, 0x1a, 0x58, 0xa1, 0x15, 0xb9, 0xd4, 0x1e, 0xa7, 0xe4, 0x11, 0xfe, 0x19, 0xc6, 0x31,
	0x84, 0x08, 0xee, 0x90, 0xa7, 0xfb, 0xc0, 0x0e, 0xad, 0xa8, 0x45, 0x75, 0x8d, 0x5d, 0xf0, 0x5f,
	0x56, 0x2b, 0xc9, 0x54, 0xe0, 0x84, 0x56, 0xe4, 0x50, 0xd3, 0x91, 0x18, 0x1a, 0x23, 0x9e, 0xcb,
	0x62, 0xc7, 0x44, 0x9d, 0xcf, 0x93, 0xe0, 0x3b, 0xed, 0xe3, 0x50, 0x5d, 0x93, 0x21, 0xb4, 0x0c,
	0x9f, 0x26, 0x79, 0xfd, 0xec, 0x63, 0x4d, 0xc9, 0x99, 0x73, 0x33, 0xd7, 0x9e, 0x73, 0x32, 0x80,
	0x33, 0xe3, 0x31, 0x49, 0x14, 0x93, 0xea, 0xc4, 0xa4, 0x0b, 0xfe, 0x84, 0xe5, 0x6b, 0xb5, 0x31,
	0x36, 0xa6, 0xeb, 0x7d, 0xda, 0xd0, 0x2c, 0x43, 0x9a, 0x31, 0xf1, 0x91, 0x2d, 0x19, 0x3e, 0xc0,
	0xff, 0x59, 0xb1, 0x90, 0x4b, 0x91, 0x2d, 0x18, 0x76, 0xaa, 0x29, 0xfe, 0xbc, 0x89, 0xd4, 0x65,
	0x7b, 0x67, 0xe1, 0x0d, 0x38, 0x94, 0xad, 0xb1, 0x5d, 0x45, 0xc7, 0x29, 0x39, 0xaf, 0xf6, 0xd3,
	0x6c, 0x8b, 0x11, 0x78, 0x6f, 0xf9, 0x9f, 0x98, 0x7d, 0xf0, 0x5e, 0x0b, 0x26, 0xf6, 0x18, 0xd4,
	0xdc, 0x43, 0x67, 0x45, 0x2e, 0xaa, 0x88, 0xfe, 0x0b, 0xf7, 0xe0, 0x9b, 0x08, 0xae, 0x6a, 0x54,
	0x07, 0xe8, 0x54, 0xb6, 0xf0, 0xf5, 0x41, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x4d, 0x16,
	0xb8, 0x76, 0x02, 0x00, 0x00,
}
